### ISSUE TITLE
please attach shutdown hooks

### ISSUE THREAD

**Issue by robinbajaj123** [FullStackLabsCa/anja-bootcamp-2024#10]
```
//TODO: please attach shutdown hooks 
```

https://github.com/FullStackLabsCa/anja-bootcamp-2024/blob/a4d68ad9ca951761662e31e70bac673ba9f7a7e1/pipeline-multithreaded-trade-processing/trade-processor-app/src/main/java/io/reactivestax/TradeProcessorRunner.java#L5

**Comment by infinityjain** [comment]
attached
