### ISSUE TITLE
remove this applicationPropertiesUtils being passed in constructor @infinityjain

### ISSUE THREAD

**Issue by robinbajaj123** [FullStackLabsCa/anja-bootcamp-2024#12]
```
    //TODO: remove this applicationPropertiesUtils being passed in constructor @infinityjain
```

https://github.com/FullStackLabsCa/anja-bootcamp-2024/blob/c7f005506c27955aea36ad73b58898286939833a/pipeline-multithreaded-trade-processing/trade-processor-app/src/main/java/io/reactivestax/service/ChunkFileGeneratorService.java#L19

**Comment by infinityjain** [comment]
removed the dependency.
