### ISSUE TITLE
Use the sample for quorum queue with DLX exchange and DLQ

### ISSUE THREAD

**Issue by robinbajaj123** [FullStackLabsCa/anja-bootcamp-2024#14]
```
            // TODO:@infinityjain Use the sample for quorum queue with DLX exchange and DLQ
```

https://github.com/FullStackLabsCa/anja-bootcamp-2024/blob/c7f005506c27955aea36ad73b58898286939833a/pipeline-multithreaded-trade-processing/trade-processor-app/src/main/java/io/reactivestax/service/FileTradeProcessorService.java#L158

**Comment by infinityjain** [comment]
fixed in version - 5
