### ISSUE TITLE
@infinityjain remove this constructor second argument

### ISSUE THREAD

**Issue by robinbajaj123** [FullStackLabsCa/anja-bootcamp-2024#15]
```
        // TODO: @infinityjain remove this constructor second argument
```

https://github.com/FullStackLabsCa/anja-bootcamp-2024/blob/c7f005506c27955aea36ad73b58898286939833a/pipeline-multithreaded-trade-processing/trade-processor-app/src/main/java/io/reactivestax/service/FileTradeProcessorService.java#L53

**Comment by infinityjain** [comment]
resolved
